import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { AuthProvider } from "@/lib/auth/authProvider";
import ToastProvider from "@/app/components/custom/ToastProvider";
import SideNevBar from "@/app/layouts/SideNevBar";
import TopNevBar from "../layouts/TopNevBar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ToastProvider />
          <TopNevBar />
          <div className="flex h-screen overflow-hidden">
            <SideNevBar />
            <div className="w-full p-5 container overflow-hidden scrollbar-hide overflow-y-scroll mx-auto">
              {children}
            </div>

          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
export const dynamic = "force-dynamic";